model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
[projects."/home/kotek/dev/hono/matching-test"]
trust_level = "trusted"

[projects."/home/kotek/dev/starup/archaive-pj"]
trust_level = "trusted"

[projects."/mnt/c/Users/kotek/dev/platformio/catchrobo_2025_dcmd"]
trust_level = "trusted"

[projects."/home/kotek/dev/c/eduterm"]
trust_level = "trusted"

[projects."/home/kotek/dev/slidev/talks"]
trust_level = "trusted"

[projects."/home/kotek/dev/js/kaigisitsu"]
trust_level = "trusted"

[projects."/home/kotek/dev/slidev/talks_ga"]
trust_level = "trusted"

[projects."/home/kotek/dev/react"]
trust_level = "trusted"

[projects."/home/kotek/dev/kansai-robocon/harurobo-2026-score-tool"]
trust_level = "trusted"

[projects."/home/kotek/dev/express/expressjs-template"]
trust_level = "trusted"

[projects."/home/kotek/dev/outline/test"]
trust_level = "trusted"

[projects."/home/kotek/dev/outline/outline-test"]
trust_level = "untrusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[features]
unified_exec = true
shell_snapshot = true
