model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"
[projects."/home/kotek/dev/hono/matching-test"]
trust_level = "trusted"

[projects."/home/kotek/dev/starup/archaive-pj"]
trust_level = "trusted"

[projects."/mnt/c/Users/kotek/dev/platformio/catchrobo_2025_dcmd"]
trust_level = "trusted"

[projects."/home/kotek/dev/c/eduterm"]
trust_level = "trusted"

[projects."/Users/suzuki.ko/dev/js/cesium-ion-test"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
