[tools]
bun = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:sd" = "latest"
"cargo:zoxide" = "latest"
chezmoi = "latest"
cmake = "3.31.9"
ghcup = "latest"
"github:cli/cli" = "latest"
"github:junegunn/fzf" = "latest"
"github:sharkdp/bat" = "latest"
go = "latest"
"go:golang.org/x/website/tour" = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:tsx" = "latest"
pnpm = "latest"
rust = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"

[settings]
experimental = true
